package models

const MODULE_NAME string = "SPL.Login"
const MOD_ERR_LOGIN_INVALID_USER int = 10001
const MOD_ERR_LOGIN_INACTIVE_USER_STATE int = 10002
const MOD_ERR_INVALID_USER_CATEGORY int = 10003
const MOD_ERR_CUSTOMER_PRODUCT_MAPPING int = 10004
const DB_DRIVER_NAME = "mysql"
