package com.opensoach.vst.Helper;

public enum AppAction {
    ON_CONNECTION,
    CHART_DATA,
    COMPLAINT_DATA,
    FEEDBACK_DATA,
    BATTERY_LEVEL,
    TASK_DATA,
    CREATE_TOKEN,
    CLAIM_TOKEN,
    CREATE_JOB_COMFIRM,
    GET_VEHICLE_DETAILS,
    UPADATE_VEHICLE_OWNER_DETAILS,
    GET_JOB_DETAILS_FOR_EXE
}