package constants

const API_BASE_URL = "/api"

const API_USER_LOGIN = API_BASE_URL + "/v1/login"
const API_USER_LOGIN_INFO = API_BASE_URL + "/v1/user/info/login"
const API_CUSTOMER_LOGIN_INFO = API_BASE_URL + "/cu/v1/customer/info/login"
const API_USER_LOGOUT = API_BASE_URL + "/v1/logout"

const API_CUSTOMER_OSU_ADD = API_BASE_URL + "/osu/v1/customer/add"
const API_CUSTOMER_OSU_UPDATE_DETAILS = API_BASE_URL + "/osu/v1/customer/update/details"
const API_CUSTOMER_CU_UPDATE_DETAILS = API_BASE_URL + "/cu/v1/customer/update/details"

const API_CUSTOMER_OSU_INFO_MASTER = API_BASE_URL + "/osu/v1/customer/info/master"
const API_CUSTOMER_CU_INFO_MASTER = API_BASE_URL + "/cu/v1/customer/info/master"
const API_CUSTOMER_OSU_INFO_DETAILS = API_BASE_URL + "/osu/v1/customer/info/details"
const API_CUSTOMER_CU_INFO_DETAILS = API_BASE_URL + "/cu/v1/customer/info/details"
const API_CUSTOMER_OSU_CORPORATE_INFO = API_BASE_URL + "/osu/v1/corporate/info"
const API_CUSTOMER_CU_CORPORATE_INFO = API_BASE_URL + "/cu/v1/corporate/info"
const API_USER_OSU_ADD = API_BASE_URL + "/osu/v1/user/add"
const API_USER_OSU_UPDATE_DETAILS = API_BASE_URL + "/osu/v1/user/update/details"
const API_USER_CU_UPDATE_DETAILS = API_BASE_URL + "/cu/v1/user/update/details"
const API_USER_OSU_UPDATE_STATE = API_BASE_URL + "/osu/v1/user/update/state"
const API_USER_CU_UPDATE_STATE = API_BASE_URL + "/cu/v1/user/update/state"
const API_USER_UPDATE_PASSWORD = API_BASE_URL + "/v1/user/update/password"
const API_CUSTOMER_OSU_LIST = API_BASE_URL + "/osu/v1/customer/list"
const API_VALIDATE_AUTH_TOKEN = API_BASE_URL + "/v1/validateauthtoken"
const API_USER_OSU_LIST = API_BASE_URL + "/osu/v1/user/list"
const API_USER_CU_LIST = API_BASE_URL + "/cu/v1/user/list"
const API_CORPORATE_OSU_LIST = API_BASE_URL + "/osu/v1/corporate/list"
