package constants

const API_BASE_URL = "/api"

const API_TASK_ADD = API_BASE_URL + "/v1/task/add"
const API_TASK_UPDATE = API_BASE_URL + "/v1/task/update"
const API_TASK_INFO_MASTER = API_BASE_URL + "/v1/task/info"
const API_TASK_LIST = API_BASE_URL + "/v1/task/list"

const API_FIELD_OPERATOR_ADD = API_BASE_URL + "/v1/fieldoperator/add"
const API_FIELD_OPERATOR_UPDATE = API_BASE_URL + "/v1/fieldoperator/update"
const API_FIELD_OPERATOR_INFO_MASTER = API_BASE_URL + "/v1/fieldoperator/info"
const API_FIELD_OPERATOR_LIST = API_BASE_URL + "/v1/fieldoperator/list"
const API_FIELD_OPERATOR_LIST_SHORT = API_BASE_URL + "/v1/fieldoperator/list/short"
const API_FIELD_OPERATOR_ASSOCIATE_SP = API_BASE_URL + "/v1/fieldoperator/associate/servicepoint"
const API_FIELD_OPERATOR_SP_ASSOCIATION_REMOVE = API_BASE_URL + "/v1/fieldoperator/associate/servicepoint/remove"
const API_FIELD_OPERATOR_ASSOCIATE_SP_INFO = API_BASE_URL + "/v1/fieldoperator/associate/servicepoint/info"

const API_COMPLAINT_ADD = API_BASE_URL + "/v1/complaint/add"
const API_COMPLAINT_UPDATE = API_BASE_URL + "/v1/complaint/update"
const API_COMPLAINT_INFO_MASTER = API_BASE_URL + "/v1/complaint/info"
const API_COMPLAINT_LIST = API_BASE_URL + "/v1/complaint/list"

const API_SERVICE_CONFIG_ADD = API_BASE_URL + "/v1/service/config/add"
const API_SERVICE_CONFIG_LIST = API_BASE_URL + "/v1/service/config/list"
const API_SERVICE_CONFIG_UPDATE = API_BASE_URL + "/v1/service/config/update"
const API_SERVICE_INSTANCE_ADD = API_BASE_URL + "/v1/service/instance/add"
const API_SERVICE_INSTANCE_LIST = API_BASE_URL + "/v1/service/instance/list"
const API_SERVICE_TXN_LIST = API_BASE_URL + "/v1/service/transaction/list"
const API_SERVICE_CONFIG_LIST_SHORT = API_BASE_URL + "/v1/service/config/list/short"
const API_SERVICE_CONFIG_COPY_TEMPLATE = API_BASE_URL + "/v1/service/config/copytemplate"
const API_SERVICE_CONFIG_INFO = API_BASE_URL + "/v1/service/config/info"
const API_SERVICE_SP_CONFIG_LIST_SHORT = API_BASE_URL + "/v1/service/spconfig/list/short"

const API_MASTER_SPC_TASK_INFO = API_BASE_URL + "/v1/master/spctask/info"
const API_MASTER_TASK_LIB_INFO = API_BASE_URL + "/v1/master/task/info"
const API_MASTER_SERV_CONF_TYPE_INFO = API_BASE_URL + "/v1/master/servconftype/info"
const API_MASTER_SP_CATEGORY_INFO = API_BASE_URL + "/v1/master/spcategory/info"

const API_SERVICE_POINT_ADD = API_BASE_URL + "/v1/servicepoint/add"
const API_SERVICE_POINT_UPDATE = API_BASE_URL + "/v1/servicepoint/update"
const API_SERVICE_POINT_LIST = API_BASE_URL + "/v1/servicepoint/list"
const API_SERVICE_POINT_CATEGORY_ADD = API_BASE_URL + "/v1/servicepoint/category/add"
const API_SERVICE_POINT_CATEGORY_LIST_SHORT = API_BASE_URL + "/v1/servicepoint/category/list/short"
const API_SERVICE_POINT_ASSOCIATE_DEVICE = API_BASE_URL + "/v1/servicepoint/associate/device"
const API_SERVICE_POINT_DEVICE_ASSOCIATION_REMOVE = API_BASE_URL + "/v1/servicepoint/associate/device/remove"
const API_SERVICE_POINT_LIST_SHORT = API_BASE_URL + "/v1/servicepoint/list/short"
const API_SERVICE_POINT_INFO = API_BASE_URL + "/v1/servicepoint/info"

const API_DEVICE_LIST_SHORT = API_BASE_URL + "/v1/device/list/short"
const API_DEVICE_LIST = API_BASE_URL + "/v1/device/list"
const API_DEVICE_NO_SP_ASSOCIATION_LIST_SHORT = API_BASE_URL + "/v1/device/list/short/noassociation"
const API_DEVICE_INFO = API_BASE_URL + "/v1/device/info"
const API_DEVICE_UPDATE = API_BASE_URL + "/v1/device/update"

const API_SPL_PROD_BASE_URL = API_BASE_URL + "/v1/splprod/baseurl"

const API_REPORT_GENERATE = API_BASE_URL + "/v1/report/generate"
const API_REPORT_VIEW = API_BASE_URL + "/v1/report/view"
const API_REPORT_LIST_SHORT = API_BASE_URL + "/v1/report/list/short"
const API_REPORT_PATIENT = API_BASE_URL + "/v1/report/patient"

const API_DASHBOARD_DEVICE_SUMMARY = API_BASE_URL + "/v1/dashboard/device/summary"
const API_DASHBOARD_LOCATION_SUMMARY = API_BASE_URL + "/v1/dashboard/location/summary"
const API_DASHBOARD_FEEDBACK_SUMMARY = API_BASE_URL + "/v1/dashboard/feedback/summary"
const API_DASHBOARD_TASK_SUMMARY = API_BASE_URL + "/v1/dashboard/task/summary"
const API_DASHBOARD_COMPLAINT_SUMMARY = API_BASE_URL + "/v1/dashboard/complaint/summary"
const API_DASHBOARD_FEEDBACKS_PER_MONTH = API_BASE_URL + "/v1/dashboard/feedback/permonth"
const API_DASHBOARD_COMPLAINTS_PER_MONTH = API_BASE_URL + "/v1/dashboard/complaint/permonth"
const API_DASHBOARD_TOP_COMPLAINTS = API_BASE_URL + "/v1/dashboard/topcomplaints"
const API_DASHBOARD_TASK_PER_MONTH = API_BASE_URL + "/v1/dashboard/task/permonth"
const API_DASHBOARD_TOP_FEEDBACKS = API_BASE_URL + "/v1/dashboard/topfeedbacks"
const API_DASHBOARD_PATIENT_SUMMARY = API_BASE_URL + "/v1/dashboard/patient/summary"

const API_FEEDBACK_LIST = API_BASE_URL + "/v1/feedback/list"

const API_PATIENT_ADD = API_BASE_URL + "/v1/patient/add"
const API_PATIENT_LIST = API_BASE_URL + "/v1/patient/list"
const API_PATIENT_UPDATE = API_BASE_URL + "/v1/patient/update"
const API_PATIENT_UPDATE_STATUS = API_BASE_URL + "/v1/patient/update/status"
const API_PATIENT_INFO_MASTER = API_BASE_URL + "/v1/patient/info"
const API_PATIENT_FILTER_INFO_MASTER = API_BASE_URL + "/v1/patient/filterinfo"
const API_PATIENT_LIST_MASTER = API_BASE_URL + "/v1/patient/list/master"
const API_PATIENT_INFO_MASTER_DETAILS = API_BASE_URL + "/v1/patient/info/details"

const API_PATIENT_ADMISSION_ADD = API_BASE_URL + "/v1/patient/admission/add"
const API_PATIENT_ADMISSION_UPDATE = API_BASE_URL + "/v1/patient/admission/update"
const API_PATIENT_ADMISSION_INFO_MASTER = API_BASE_URL + "/v1/patient/admission/info"
const API_PATIENT_ADMISSION_INFO_STATUS = API_BASE_URL + "/v1/patient/admission/info/status"
const API_PATIENT_ADMISSION_INFO_DETAILS = API_BASE_URL + "/v1/patient/admission/info/details"

const API_PATIENT_PERSONAL_DETAILS_ADD = API_BASE_URL + "/v1/patient/personaldetails/add"
const API_PATIENT_PERSONAL_DETAILS_UPDATE = API_BASE_URL + "/v1/patient/personaldetails/update"
const API_PATIENT_PERSONAL_INFO_MASTER = API_BASE_URL + "/v1/patient/personaldetails/info"
const API_PATIENT_PERSONAL_DETAILS_UPDATE_PERSON_ACCOMPANYING = API_BASE_URL + "/v1/patient/personaldetails/update/personaccompanying"

const API_PATIENT_MEDICAL_DETAILS_ADD = API_BASE_URL + "/v1/patient/medicaldetails/add"
const API_PATIENT_MEDICAL_DETAILS_UPDATE = API_BASE_URL + "/v1/patient/medicaldetails/update"
const API_PATIENT_MEDICAL_INFO_MASTER = API_BASE_URL + "/v1/patient/medicaldetails/info"

const API_PATIENT_MEDICAL_DETAILS_UPDATE_PRESENT_COMPLAINTS = API_BASE_URL + "/v1/patient/medicaldetails/update/presentcomplaints"
const API_PATIENT_MEDICAL_DETAILS_UPDATE_REASON_FOR_ADMISSION = API_BASE_URL + "/v1/patient/medicaldetails/update/reasonforadmission"
const API_PATIENT_MEDICAL_DETAILS_UPDATE_HISTORY_PRESENT_ILLNESS = API_BASE_URL + "/v1/patient/medicaldetails/update/historypresentillness"
const API_PATIENT_MEDICAL_DETAILS_UPDATE_PAST_HISTORY = API_BASE_URL + "/v1/patient/medicaldetails/update/pasthistory"
const API_PATIENT_MEDICAL_DETAILS_UPDATE_TREATMENT_BEFORE_ADMISSION = API_BASE_URL + "/v1/patient/medicaldetails/update/treatmentbeforeadmission"
const API_PATIENT_MEDICAL_DETAILS_UPDATE_INVESTIGATION_BEFORE_ADMISSION = API_BASE_URL + "/v1/patient/medicaldetails/update/investigationbeforeadmission"
const API_PATIENT_MEDICAL_DETAILS_UPDATE_FAMILY_HISTORY = API_BASE_URL + "/v1/patient/medicaldetails/update/familyhistory"
const API_PATIENT_MEDICAL_DETAILS_UPDATE_ALLERGIES = API_BASE_URL + "/v1/patient/medicaldetails/update/allergies"
const API_PATIENT_MEDICAL_DETAILS_UPDATE_PERSONAL_HISTORY = API_BASE_URL + "/v1/patient/medicaldetails/update/personalhistory"

const API_PATIENT_ACTION_TXN_LIST = API_BASE_URL + "/v1/patient/list/actiontxn"
const API_PATIENT_DOCTORS_ORDERS_LIST = API_BASE_URL + "/v1/patient/list/doctororders"
const API_PATIENT_TREATMENT_LIST = API_BASE_URL + "/v1/patient/list/treatment"
const API_PATIENT_PATHOLOGY_RECORD_LIST = API_BASE_URL + "/v1/patient/list/pathologyrecord"

const API_PATIENT_CONFIG_LIST = API_BASE_URL + "/v1/patient/list/patientconf"
const API_PATIENT_CONFIG_INFO = API_BASE_URL + "/v1/patient/config/info"
const API_PATIENT_CONFIG_UPDATE = API_BASE_URL + "/v1/patient/config/update"

const API_PATIENT_DOCTORS_ORDERS_INFO = API_BASE_URL + "/v1/patient/info/doctorsorders"
const API_PATIENT_PATHOLOGY_RECORDS_INFO = API_BASE_URL + "/v1/patient/info/pathologyrecords"
const API_PATIENT_TREATMENT_INFO = API_BASE_URL + "/v1/patient/info/treatment"

const API_DOCUMENT_DOWNLOAD = API_BASE_URL + "/v1/document/download"
const API_DOCUMENT_UPLOAD = API_BASE_URL + "/v1/document/upload"
const API_DEVICE_DOCUMENT_UPLOAD = API_BASE_URL + "/v1/document/upload/ep"
const API_DEVICE_DOCUMENT_DOWNLOAD = API_BASE_URL + "/v1/document/download/ep"

const API_PATIENT_TREATMENT_ADD = API_BASE_URL + "/v1/patient/treatment/add"
const API_PATIENT_PATHOLOGY_RECORD_ADD = API_BASE_URL + "/v1/patient/pathologyrecord/add"
