export enum SERVER_WORKER_MSG_TYPE {
    NONE = 0,
    INIT_SERVER_INTERFACE = 1,
    CONNECT_SERVER_INTERFACE = 1,
    CLOSE_SERVER_INTERFACE = 2,
    SEND_MESSAGE = 3
}

export enum APP_MODE {
    NONE=0,
    SHARED_DEVICE=1,
    USER_DEVICE=2
}
