export enum SERVER_WORKER_MSG_TYPE {
    NONE = 0,
    INIT_SERVER_INTERFACE = 1,
    CONNECT_SERVER_INTERFACE = 2,
    CLOSE_SERVER_INTERFACE = 3,
    SEND_MESSAGE = 4
}

export enum SERVER_WORKER_EVENT_MSG_TYPE {
    NONE = 0,
    SERVER_CONNECTED = 1,
    SERVER_DISCONNECTED = 2,
    DATA_RECEIVED=3,
    NOTIFICATION_DATA_RECEIVED=4
}

export enum APP_MODE {
    NONE=0,
    SHARED_DEVICE=1,
    USER_DEVICE=2
}
