package constants

const API_AUTHORIZATION_ROUTER_GROUP_KEY = "ALL"
const API_BASE_URL = "/api"

const API_USER_LOGIN = API_BASE_URL + "/v1/login"
const API_USER_LOGIN_INFO = API_BASE_URL + "/v1/user/info/login"
const API_CUSTOMER_LOGIN_INFO = API_BASE_URL + "/cu/v1/customer/info/login"
const API_USER_LOGOUT = API_BASE_URL + "/v1/logout"
const API_VALIDATE_AUTH_TOKEN = API_BASE_URL + "/v1/validateauthtoken"

const API_CUSTOMER_OSU_ADD = API_BASE_URL + "/osu/v1/customer/add"
const API_CUSTOMER_OSU_UPDATE_DETAILS = API_BASE_URL + "/osu/v1/customer/update/details"
const API_CUSTOMER_CU_UPDATE_DETAILS = API_BASE_URL + "/cu/v1/customer/update/details"
const API_CUSTOMER_OSU_INFO_MASTER = API_BASE_URL + "/osu/v1/customer/info/master"
const API_CUSTOMER_CU_INFO_MASTER = API_BASE_URL + "/cu/v1/customer/info/master"
const API_CUSTOMER_OSU_INFO_DETAILS = API_BASE_URL + "/osu/v1/customer/info/details"
const API_CUSTOMER_CU_INFO_DETAILS = API_BASE_URL + "/cu/v1/customer/info/details"
const API_CUSTOMER_OSU_CORPORATE_INFO = API_BASE_URL + "/osu/v1/corporate/info"
const API_CUSTOMER_CU_CORPORATE_INFO = API_BASE_URL + "/cu/v1/corporate/info"
const API_CUSTOMER_OSU_LIST = API_BASE_URL + "/osu/v1/customer/list"
const API_CUST_OSU_ASSOCIATE_CUST_WITH_PROD = API_BASE_URL + "/osu/v1/customer/associate/product"
const API_CUSTOMER_PRODUCT_ASSCOCIATION_LIST = API_BASE_URL + "/osu/v1/customer/list/productassociation"
const API_CUSTOMER_PRODUCT_ASSCOCIATION_UPDATE = API_BASE_URL + "/osu/v1/customer/productassociation/update"
const API_CUSTOMER_OSU_UPDATE = API_BASE_URL + "/osu/v1/customer/update"
const API_CUSTOMER_OSU_LIST_SHORT = API_BASE_URL + "/osu/v1/customer/list/short"
const API_CUSTOMER_SERVICE_POINT_ASSCOCIATION = API_BASE_URL + "/osu/v1/customer/association/servicepoint"
const API_CUSTOMER_SERVICE_POINT_ASSCOCIATION_UPDATE = API_BASE_URL + "/osu/v1/customer/association/servicepoint/update"

const API_USER_OSU_ADD = API_BASE_URL + "/osu/v1/user/add"
const API_USER_OSU_UPDATE_DETAILS = API_BASE_URL + "/osu/v1/user/update/details"
const API_USER_CU_UPDATE_DETAILS = API_BASE_URL + "/cu/v1/user/update/details"
const API_USER_OSU_UPDATE_STATE = API_BASE_URL + "/osu/v1/user/update/state"
const API_USER_CU_UPDATE_STATE = API_BASE_URL + "/cu/v1/user/update/state"
const API_USER_UPDATE_PASSWORD = API_BASE_URL + "/v1/user/update/password"
const API_USER_OSU_LIST = API_BASE_URL + "/osu/v1/user/list"
const API_USER_CU_LIST = API_BASE_URL + "/cu/v1/user/list"
const API_USER_OSU_ASSOCIATE_USER_WITH_CUST = API_BASE_URL + "/osu/v1/user/associate/customer"
const API_USER_CU_ASSOCIATE_USER_WITH_CUST = API_BASE_URL + "/cu/v1/user/associate/customer"
const API_USER_OSU_INFO_DETAILS = API_BASE_URL + "/osu/v1/user/info/details"
const API_USER_CU_INFO_DETAILS = API_BASE_URL + "/cu/v1/user/info/details"
const API_UROLE_OSU_LIST = API_BASE_URL + "/osu/v1/urole/list"
const API_UROLE_LIST = API_BASE_URL + "/v1/urole/list"
const API_USER_PRODUCT_ASSCOCIATION_OSU_LIST = API_BASE_URL + "/osu/v1/user/list/productassociation"
const API_USER_PRODUCT_ASSCOCIATION_OSU_UPDATE = API_BASE_URL + "/osu/v1/user/productassociation/update"
const API_USER_OSU_UPDATE = API_BASE_URL + "/osu/v1/user/update"
const API_USER_OSU_INFO_MASTER = API_BASE_URL + "/osu/v1/user/info/master"
const API_USER_CU_INFO_MASTER = API_BASE_URL + "/cu/v1/user/info/master"
const API_USER_CU_ROLE_ADD = API_BASE_URL + "/cu/role/v1/user/add"
const API_USER_CU_ROLE_INFO_MASTER = API_BASE_URL + "/cu/role/v1/user/info/master"
const API_USER_CU_ROLE_INFO_DETAILS = API_BASE_URL + "/cu/role/v1/user/info/details"
const API_USER_CU_ROLE_UPDATE = API_BASE_URL + "/cu/role/v1/user/update"
const API_USER_CU_ROLE_UPDATE_DETAILS = API_BASE_URL + "/cu/role/v1/user/update/details"
const API_USER_ACTIVATION = API_BASE_URL + "/v1/user/activation"

const API_CORPORATE_OSU_LIST = API_BASE_URL + "/osu/v1/corporate/list"
const API_CORPORATE_OSU_LIST_SHORT = API_BASE_URL + "/osu/v1/corporate/list/short"
const API_CORPORATE_OSU_ADD = API_BASE_URL + "/osu/v1/corporate/add"
const API_CORPORATE_OSU_UPDATE = API_BASE_URL + "/osu/v1/corporate/update"
const API_CORPORATE_OSU_INFO_MASTER = API_BASE_URL + "/osu/v1/corporate/info/master"

const API_DEVICE_OSU_ADD = API_BASE_URL + "/osu/v1/device/add"
const API_DEVICE_OSU_UPDATE_STATE = API_BASE_URL + "/osu/v1/device/update/state"
const API_DEVICE_OSU_UPDATE_DETAILS = API_BASE_URL + "/osu/v1/device/update/details"
const API_DEVICE_CU_UPDATE_DETAILS = API_BASE_URL + "/cu/v1/device/update/details"
const API_DEVICE_OSU_LIST = API_BASE_URL + "/osu/v1/device/list"
const API_DEVICE_CU_LIST = API_BASE_URL + "/cu/v1/device/list"
const API_DEVICE_OSU_ASSOCIATE_DEV_WITH_CUST = API_BASE_URL + "/osu/v1/device/associate/customer"
const API_DEVICE_OSU_ASSOCIATE_DEV_WITH_CUSTPRODUCT = API_BASE_URL + "/osu/v1/device/associate/customerproduct"
const API_DEVICE_OSU_INFO_DETAILS = API_BASE_URL + "/osu/v1/device/info/details"
const API_DEVICE_CU_INFO_DETAILS = API_BASE_URL + "/cu/v1/device/info/details"
const API_DEVICE_PRODUCT_ASSCOCIATION_LIST = API_BASE_URL + "/osu/v1/device/list/productassociation"
const API_DEVICE_OSU_LIST_SHORT = API_BASE_URL + "/osu/v1/device/list/short"
const API_DEVICE_OSU_INFO_MASTER = API_BASE_URL + "/osu/v1/device/info/master"

const API_DBINSTANCE_OSU_LIST = API_BASE_URL + "/osu/v1/dbinstance/list"
const API_PRODUCT_OSU_LIST = API_BASE_URL + "/osu/v1/product/list"

const API_ENDPOINT_DEVICE_AUTH = API_BASE_URL + "/v1/endpoint/deviceauthorization"
const API_ENDPOINT_DEVICE_USER_AUTH = API_BASE_URL + "/v1/endpoint/userauthorization"
const API_ENDPOINT_DEVICE_USER_LIST = API_BASE_URL + "/v1/endpoint/userlist"
