package constants

const API_BASE_URL = "/api"

const API_TASK_ADD = API_BASE_URL + "/v1/task/add"
const API_TASK_UPDATE = API_BASE_URL + "/v1/task/update"
const API_TASK_INFO_MASTER = API_BASE_URL + "/v1/task/info"
const API_TASK_LIST = API_BASE_URL + "/v1/task/list"

const API_FIELD_OPERATOR_ADD = API_BASE_URL + "/v1/fieldoperator/add"
const API_FIELD_OPERATOR_UPDATE = API_BASE_URL + "/v1/fieldoperator/update"
const API_FIELD_OPERATOR_INFO_MASTER = API_BASE_URL + "/v1/fieldoperator/info"
const API_FIELD_OPERATOR_LIST = API_BASE_URL + "/v1/fieldoperator/list"
const API_FIELD_OPERATOR_LIST_SHORT = API_BASE_URL + "/v1/fieldoperator/list/short"
const API_FIELD_OPERATOR_ASSOCIATE_SP = API_BASE_URL + "/v1/fieldoperator/associate/servicepoint"
const API_FIELD_OPERATOR_SP_ASSOCIATION_REMOVE = API_BASE_URL + "/v1/fieldoperator/associate/servicepoint/remove"
const API_FIELD_OPERATOR_ASSOCIATE_SP_INFO = API_BASE_URL + "/v1/fieldoperator/associate/servicepoint/info"

const API_COMPLAINT_ADD = API_BASE_URL + "/v1/complaint/add"
const API_COMPLAINT_UPDATE = API_BASE_URL + "/v1/complaint/update"
const API_COMPLAINT_INFO_MASTER = API_BASE_URL + "/v1/complaint/info"
const API_COMPLAINT_LIST = API_BASE_URL + "/v1/complaint/list"

const API_SERVICE_CONFIG_ADD = API_BASE_URL + "/v1/service/config/add"
const API_SERVICE_CONFIG_LIST = API_BASE_URL + "/v1/service/config/list"
const API_SERVICE_CONFIG_UPDATE = API_BASE_URL + "/v1/service/config/update"
const API_SERVICE_INSTANCE_ADD = API_BASE_URL + "/v1/service/instance/add"
const API_SERVICE_INSTANCE_LIST = API_BASE_URL + "/v1/service/instance/list"
const API_SERVICE_TXN_LIST = API_BASE_URL + "/v1/service/transaction/list"
const API_SERVICE_CONFIG_LIST_SHORT = API_BASE_URL + "/v1/service/config/list/short"
const API_SERVICE_CONFIG_COPY_TEMPLATE = API_BASE_URL + "/v1/service/config/copytemplate"
const API_SERVICE_CONFIG_INFO = API_BASE_URL + "/v1/service/config/info"

const API_MASTER_SPC_TASK_INFO = API_BASE_URL + "/v1/master/spctask/info"
const API_MASTER_TASK_LIB_INFO = API_BASE_URL + "/v1/master/task/info"
const API_MASTER_SERV_CONF_TYPE_INFO = API_BASE_URL + "/v1/master/servconftype/info"
const API_MASTER_SP_CATEGORY_INFO = API_BASE_URL + "/v1/master/spcategory/info"

const API_SERVICE_POINT_ADD = API_BASE_URL + "/v1/servicepoint/add"
const API_SERVICE_POINT_UPDATE = API_BASE_URL + "/v1/servicepoint/update"
const API_SERVICE_POINT_LIST = API_BASE_URL + "/v1/servicepoint/list"
const API_SERVICE_POINT_CATEGORY_ADD = API_BASE_URL + "/v1/servicepoint/category/add"
const API_SERVICE_POINT_CATEGORY_LIST_SHORT = API_BASE_URL + "/v1/servicepoint/category/list/short"
const API_SERVICE_POINT_ASSOCIATE_DEVICE = API_BASE_URL + "/v1/servicepoint/associate/device"
const API_SERVICE_POINT_DEVICE_ASSOCIATION_REMOVE = API_BASE_URL + "/v1/servicepoint/associate/device/remove"
const API_SERVICE_POINT_LIST_SHORT = API_BASE_URL + "/v1/servicepoint/list/short"
const API_SERVICE_POINT_INFO = API_BASE_URL + "/v1/servicepoint/info"
const API_SERVICE_POINT_CONFIG_LIST_SHORT = API_BASE_URL + "/v1/servicepoint/config/list/short"

const API_DEVICE_LIST_SHORT = API_BASE_URL + "/v1/device/list/short"
const API_DEVICE_LIST = API_BASE_URL + "/v1/device/list"
const API_DEVICE_NO_SP_ASSOCIATION_LIST_SHORT = API_BASE_URL + "/v1/device/list/short/noassociation"
const API_DEVICE_INFO = API_BASE_URL + "/v1/device/info"
const API_DEVICE_UPDATE = API_BASE_URL + "/v1/device/update"

const API_SPL_PROD_BASE_URL = API_BASE_URL + "/v1/splprod/baseurl"

const API_REPORT_GENERATE = API_BASE_URL + "/v1/report/generate"
const API_REPORT_INFO = API_BASE_URL + "/v1/report/info"
const API_REPORT_LIST_SHORT = API_BASE_URL + "/v1/report/list/short"
const API_REPORT_LOCATION_SUMMARY = API_BASE_URL + "/v1/report/location/summary"

const API_DASHBOARD_DEVICE_SUMMARY = API_BASE_URL + "/v1/dashboard/device/summary"
const API_DASHBOARD_LOCATION_SUMMARY = API_BASE_URL + "/v1/dashboard/location/summary"
const API_DASHBOARD_FEEDBACK_SUMMARY = API_BASE_URL + "/v1/dashboard/feedback/summary"
const API_DASHBOARD_TASK_SUMMARY = API_BASE_URL + "/v1/dashboard/task/summary"
const API_DASHBOARD_COMPLAINT_SUMMARY = API_BASE_URL + "/v1/dashboard/complaint/summary"
const API_DASHBOARD_FEEDBACKS_PER_MONTH = API_BASE_URL + "/v1/dashboard/feedback/permonth"
const API_DASHBOARD_COMPLAINTS_PER_MONTH = API_BASE_URL + "/v1/dashboard/complaint/permonth"
const API_DASHBOARD_TOP_COMPLAINTS = API_BASE_URL + "/v1/dashboard/topcomplaints"
const API_DASHBOARD_TASK_PER_MONTH = API_BASE_URL + "/v1/dashboard/task/permonth"
